export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEWS = 'ADD_REVIEWS';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const LOCATIONS_LOADING = 'LOCATIONS_LOADED';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';
export const REVIEWS_LOADING = 'REVIEWS_LOADING'
export const REVIEWS_FAILED = 'REVIEWS_FAILED';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';




